### ISSUE TITLE
Xiaomi 12tPro

### ISSUE THREAD

**Issue by jjoeshua** [Xposed-Modules-Repo/com.gswxxn.camerasnap#1]
I install module, get options in camera but , when I lock screen , It won't take video or picture when I press volume down...

Is this can help:

`Crash unexpectedly: java.lang.RuntimeException: Unable to create service com.android.camera.snap.SnapService: java.lang.SecurityException: Permission Denial: startForeground from pid=24249, uid=10123 requires android.permission.FOREGROUND_SERVICE
	at android.app.ActivityThread.handleCreateService(Unknown Source:267)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:778)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=24249, uid=10123 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createExceptionOrNull(Unknown Source:7)
	at android.os.Parcel.createException(Unknown Source:0)
	at android.os.Parcel.readException(Unknown Source:11)
	at android.os.Parcel.readException(Unknown Source:10)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(Unknown Source:40)
	at android.app.Service.startForeground(Unknown Source:15)
	at com.android.camera.snap.SnapService.onCreate(Unknown Source:78)
	at android.app.ActivityThread.handleCreateService(Unknown Source:184)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(Unknown Source:63)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(Unknown Source:167)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(Unknown Source:27)
	at com.android.server.am.ActivityManagerService.setServiceForeground(Unknown Source:12)
	at android.app.IActivityManager$Stub.onTransact(Unknown Source:5304)`

**Comment by GSWXXN** [comment]
It seems like your camera did not declare foreground service permission. I am not sure why this permission got removed on your device, but you can try using this third-party modified version of the camera. 

https://github.com/a406010503/Miui_Camera

**Comment by jjoeshua** [comment]
I download Leica camera and its work , module work, but on miu still doesnt work...

**Comment by GSWXXN** [comment]
same error?

**Comment by GSWXXN** [comment]
Your original problem has been solved. 
Plz download [here](https://github.com/Xposed-Modules-Repo/com.gswxxn.camerasnap/releases/tag/12-1.2). After updating the module,  remember to check `System Framework` in the LSPosed module scope, although it is not in the recommended apps list
