### ISSUE TITLE
14ultra无法使用（无设置菜单）

### ISSUE THREAD

**Issue by cibimo** [Xposed-Modules-Repo/com.gswxxn.camerasnap#3]
设备型号 xiaomi 14ultra
相机版本 5.2.001240.0
系统版本 hyperos 1.0.3.0
希望作者添加支持（感谢感谢）

**Comment by GSWXXN** [comment]
请提供一下lsp的日志

**Comment by cibimo** [comment]
清空日志之后打开相机后打开相机设置后抓取到的
```
----part 2 start----
[ 2024-02-28T17:02:08.038    10141: 29679: 29679 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~FfOgeHBjAZBP3bWr_7wlIA==/com.sevtinge.hyperceiler-QP1j33biKAFx3i_3q1vgww==/base.apk
[ 2024-02-28T17:02:08.045    10141: 29679: 29679 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-02-28T17:02:08.078    10141: 29679: 29679 I/LSPosed-Bridge  ] Loading legacy module com.gswxxn.camerasnap from /data/app/~~TYX25J_fdgBAKSs-YQGiJw==/com.gswxxn.camerasnap-a_NPMdBvBmVu3K6JE4Eujw==/base.apk
[ 2024-02-28T17:02:08.080    10141: 29679: 29679 I/LSPosed-Bridge  ]   Loading class com.gswxxn.camerasnap.hook.HookEntry_YukiHookXposedInit
[ 2024-02-28T17:02:08.279    10141: 29679: 29679 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][I][com.android.camera] load members from dexkit
[ 2024-02-28T17:02:08.660    10141: 29679: 29679 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][E][com.android.camera] not found mGetSupportSnap!!!
[ 2024-02-28T17:02:08.672    10141: 29679: 29679 I/LSPosed-Bridge  ] [UnlockMIUICameraSnap][E][com.android.camera] Try to hook [protected void android.content.ContextWrapper.attachBaseContext(android.content.Context)] got an exception
[ 2024-02-28T17:02:08.672    10141: 29679: 29679 E/LSPosed-Bridge  ] java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at k0.l.a(Unknown Source:329)
	at g.m.j(Unknown Source:138)
	at m0.a.c(Unknown Source:665)
	at w0.b.a(Unknown Source:21)
	at x0.g.afterHookedMethod(Unknown Source:13)
	at oPC.th.gT.mTf.a.oXVZxy.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.attachBaseContext(Unknown Source:11)
	at com.android.camera.CameraAppImpl.attachBaseContext(Unknown Source:109)
	at android.app.Application.attach(Application.java:368)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1290)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1487)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1424)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7451)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[ 2024-02-28T17:02:09.191    10163: 30083: 30083 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~FfOgeHBjAZBP3bWr_7wlIA==/com.sevtinge.hyperceiler-QP1j33biKAFx3i_3q1vgww==/base.apk
[ 2024-02-28T17:02:09.205    10163: 30083: 30083 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-02-28T17:02:15.944    10252: 30977: 30977 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~FfOgeHBjAZBP3bWr_7wlIA==/com.sevtinge.hyperceiler-QP1j33biKAFx3i_3q1vgww==/base.apk
[ 2024-02-28T17:02:15.954    10252: 30977: 30977 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-02-28T17:02:16.004    10139: 31007: 31007 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~FfOgeHBjAZBP3bWr_7wlIA==/com.sevtinge.hyperceiler-QP1j33biKAFx3i_3q1vgww==/base.apk
[ 2024-02-28T17:02:16.014    10139: 31007: 31007 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
```

**Comment by GSWXXN** [comment]
那麻烦再提取一下相机app吧

**Comment by cibimo** [comment]
https://www.123pan.com/s/BuiA-y2Msv.html  提取码：lvnt

**Comment by GSWXXN** [comment]
https://github.com/GSWXXN/UnlockMIUICameraSnap/commit/6f6ae25855239545a41d3a34958cd69cac01819d
已适配 请更新测试

**Comment by cibimo** [comment]
测试了，没问题，谢谢作者
